# Learn more about configuring your app at
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4079667916c09d8b2bc3a10df6c992c5"
name = "HairGrab Core"
application_url = "https://seller.hairgrab.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders-create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders-paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/refunds-create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/fulfillment-event-create"
  topics = [ "fulfillment_events/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/same-day-fulfillment"
  topics = [ "fulfillment_orders/order_routing_complete", "fulfillment_orders/fulfillment_request_submitted", "fulfillment_orders/cancellation_request_submitted" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
scopes = "read_orders,write_orders,read_products,write_products,read_shopify_payments_payouts,read_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_locations,read_inventory,write_inventory,write_files,read_shipping,write_shipping,write_app_proxy,write_fulfillments,write_assigned_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://seller.hairgrab.com/auth/callback"
]

[app_proxy]
url = "/favorites-proxy"
prefix = "apps"
subpath = "hairgrab-favorites"
